repos:
  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
    hooks:
      - id: actionlint
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff lint
        entry: uv run --locked ruff check
        language: system
        types_or: [python, pyi]
        pass_filenames: false
      - id: ruff-format
        name: Ruff format check
        entry: uv run --locked ruff format --check
        language: system
        types_or: [python, pyi]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run --locked mypy
        language: system
        types_or: [python, pyi]
        pass_filenames: false
